---

- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl
  when:
    - not reboot

- name: Restart rke2-server
  ansible.builtin.service:
    state: restarted
    name: rke2-server
  throttle: 1
  when:
    - not reboot

- name: Restart rke2-agent
  ansible.builtin.service:
    state: restarted
    name: rke2-agent
  throttle: 1
  when:
    - not reboot

- name: Reboot the machine
  ansible.builtin.reboot:
    reboot_timeout: 300
  throttle: 1
  when:
    - reboot

- name: Reload NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: reloaded
  when:
    - not reboot
