---
- name: Add audit policy configuration file
  vars:
    file_contents: "{{ lookup('file', rke2_audit_policy_config_file_path) }}"
  ansible.builtin.template:
    src: ansible_header.j2
    dest: "/etc/rancher/rke2/audit-policy.yaml"
    mode: '0640'
    owner: root
    group: root
  when:
    - rke2_audit_policy_config_file_path|length != 0
  notify: "Restart {{ service_name }}"

- name: Remove audit policy configuration file
  when:
    - rke2_audit_policy_config_file_path|length == 0
  block:
    - name: Check that the audit policy config file exists
      ansible.builtin.stat:
        path: "/etc/rancher/rke2/audit-policy.yaml"
      register: stat_result

    - name: "Check that the audit policy config file has ansible managed comments"
      ansible.builtin.lineinfile:
        name: "/etc/rancher/rke2/audit-policy.yaml"
        line: '## This is an Ansible managed file, contents will be overwritten ##'
        state: present
      check_mode: yes
      register: ansible_managed_check
      when: stat_result.stat.exists | bool is true

    - name: Remove the audit policy config file if exists and has ansible managed comments
      ansible.builtin.file:
        path: "/etc/rancher/rke2/audit-policy.yaml"
        state: absent
      when:
        - ansible_managed_check.changed | bool is false
      notify: "Restart {{ service_name }}"
