---

- name: Populate service facts
  ansible.builtin.service_facts: {}

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set for install method of tarball
  ansible.builtin.set_fact:
    install_method: tarball
  when: |-
      ((ansible_facts['os_family'] != 'RedHat' and ansible_facts['os_family'] != 'Rocky') or
      rke2_install_tarball_url != "" or
      rke2_local_install_tarball_path != "" or
      rke2_force_tarball_install|bool)

- name: Set for install method of rpm
  ansible.builtin.set_fact:
    install_method: rpm
  when:
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'
    - rke2_local_install_tarball_path == ""
    - rke2_install_tarball_url == ""
    - not rke2_force_tarball_install|bool

- name: Set as server
  ansible.builtin.set_fact:
    service_name: rke2-server
  when:
    - inventory_hostname in groups['rke2_servers']

- name: Set as agent
  ansible.builtin.set_fact:
    service_name: rke2-agent
  when:
    - inventory_hostname in groups.get('rke2_agents', [])

- name: Satisfy OS Pre-Reqs
  ansible.builtin.include_tasks: pre_reqs.yml

- name: Has rke2 been installed already
  ansible.builtin.include_tasks: previous_install.yml

- name: Check for images bundle
  ansible.builtin.include_tasks: images_bundle.yml
  when:
    - rke2_images_urls != [] or
      rke2_images_local_tarball_path != []

- name: Determine rke2_version to install
  ansible.builtin.include_tasks: calculate_rke2_version.yml
  when:
    - rke2_local_install_tarball_path == ""
    - rke2_install_tarball_url == ""

- name: Tarball Install
  ansible.builtin.include_tasks: tarball_install.yml
  when:
    - install_method == "tarball"

- name: RPM Install
  ansible.builtin.include_tasks: rpm_install.yml
  when:
    - install_method == "rpm"

- name: Set rke2 configuration files
  ansible.builtin.include_tasks: configure_rke2.yml

- name: RKE2 on first node
  ansible.builtin.include_tasks: first_server.yml
  when:
    - inventory_hostname in groups['rke2_servers'][0]

- name: RKE2 on all other nodes
  ansible.builtin.include_tasks: other_nodes.yml
  when:
    - inventory_hostname in groups['rke2_servers'][1:] or
      inventory_hostname in groups.get('rke2_agents', [])

- name: Configure kubectl,crictl,ctr
  ansible.builtin.include_tasks: utilities.yml
  when:
    - inventory_hostname in groups['rke2_servers']

- name: Configure cluster manifests
  ansible.builtin.include_tasks: add-manifest-addons.yml
  vars:
    src: "{{ rke2_cluster_manifest_config_file_path }}"
  when:
    - inventory_hostname in groups['rke2_servers'][0]
