---

- name: Determine rke2_version to install
  ansible.builtin.include_tasks: calculate_rke2_version.yml

# Add RKE2 Common repo
- name: Add the rke2-common repo RHEL/CentOS/Rocky
  ansible.builtin.yum_repository:
    name: "{{ rke2_common_yum_repo.name }}"
    description: "{{ rke2_common_yum_repo.description }}"
    baseurl: "{{ rke2_common_yum_repo.baseurl }}"
    gpgcheck: "{{ rke2_common_yum_repo.gpgcheck }}"
    gpgkey: "{{ rke2_common_yum_repo.gpgkey }}"
    enabled: "{{ rke2_common_yum_repo.enabled }}"
  when:
    - ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Rocky"
    - ansible_facts['distribution_major_version'] == "7" or
      ansible_facts['distribution_major_version'] == "8" or
      ansible_facts['distribution_major_version'] == "9"

# Add RKE2 versioned repo
- name: Add the rke2 versioned repo CentOS/RHEL/Rocky
  ansible.builtin.yum_repository:
    name: "{{ rke2_versioned_yum_repo.name }}"
    description: "{{ rke2_versioned_yum_repo.description }}"
    baseurl: "{{ rke2_versioned_yum_repo.baseurl }}"
    gpgcheck: "{{ rke2_versioned_yum_repo.gpgcheck }}"
    gpgkey: "{{ rke2_versioned_yum_repo.gpgkey }}"
    enabled: "{{ rke2_versioned_yum_repo.enabled }}"
  when:
    - ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Rocky"
    - ansible_facts['distribution_major_version'] == "7" or
      ansible_facts['distribution_major_version'] == "8" or
      ansible_facts['distribution_major_version'] == "9"

- name: YUM-Based Install
  ansible.builtin.yum:
    name: "{{ service_name }}-{{ rke2_version_rpm }}"
    state: latest  # noqa package-latest
  notify: "Restart {{ service_name }}"
