---

- name: Add manifest addons files
  ansible.builtin.copy:
    src: "{{ src }}"
    dest: "/var/lib/rancher/rke2/server/manifests/ansible_managed_manifests/"
    mode: '0640'
    owner: root
    group: root
